# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mohamedaichaouiii  # ✅ updated to your username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show git status
      - run: git status

      # Push the changes using your personal token
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}  # ✅ use your PAT secret here
          branch: master
          force: true

      # Deploy to GitHub Pages from 'output' branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # ✅ use your PAT secret here too
